In [1]:
# Creating Arrays

import numpy as np 
import time

# zeros, ones, arange, linspace
a_zeros = np.zeros((3, 4))              # 3x4 array of zeros
a_ones  = np.ones((2, 3, 2))           # 2x3x2 array of ones
a_arange = np.arange(10, 50, 5)        # [10 15 20 25 30 35 40 45]
a_linspace = np.linspace(0, 1, 5)      # [0.  0.25 0.5 0.75 1. ]

# Random arrays
a_rand = np.random.random((3, 3))      # 3x3 random floats [0,1)
a_randint = np.random.randint(0, 10, size=(2, 5))  # 2x5 random ints

# From list
py_list = [1, 2, 3, 4]
a_from_list = np.array(py_list)        # array([1,2,3,4])

In [ ]:
# Array Indexing & Slicing

arr = np.arange(10)
print(arr[3])        # 3
print(arr[2:5])      # [2 3 4]
print(arr[::-1])     # reverse

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0, 2])           # 3 (row 0, col 2)
print(arr2d[:, 1])           # second column: [2,5,8]
print(arr2d[1:, :2])         # rows 1-2, cols 0-1: [[4,5],[7,8]]

3
[2 3 4]
[9 8 7 6 5 4 3 2 1 0]
3
[2 5 8]
[[4 5]
 [7 8]]


In [3]:
# Reshaping Arrays

a = np.arange(12)
b = a.reshape(3, 4)        # 3 rows, 4 columns
c = a.reshape(2, -1)       # -1 infers the size: 2x6

# Flattening
flat = b.ravel()           # 1D view
flat2 = b.flatten()        # copy

In [4]:
# Broadcasting Concept

# Adding a scalar
arr = np.array([1,2,3])
print(arr + 10)            # [11 12 13]

# Broadcasting between different shapes
matrix = np.ones((3, 4))
row_vec = np.array([1, 2, 3, 4])
print(matrix + row_vec)    # row added to each row of matrix

col_vec = np.array([[10],[20],[30]])
print(matrix + col_vec)    # column added to each column

[11 12 13]
[[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]
[[11. 11. 11. 11.]
 [21. 21. 21. 21.]
 [31. 31. 31. 31.]]


In [5]:
# Array Operations

# Element-wise Operations

x = np.array([1,2,3])
y = np.array([4,5,6])
print(x + y)       # [5 7 9]
print(x * y)       # [4 10 18]
print(x ** 2)      # [1 4 9]
print(x > 2)       # [False False  True]

# Matrix multiplication (dot)
print(x @ y)       # 32  (1*4 + 2*5 + 3*6)

[5 7 9]
[ 4 10 18]
[1 4 9]
[False False  True]
32


In [6]:
# Mathematical Functions

a = np.array([0, np.pi/2, np.pi])
print(np.sin(a))      # [0. 1. 1.2e-16]
print(np.exp([1,2]))  # [2.718 7.389]
print(np.sqrt([4,9,16])) # [2. 3. 4.]
print(np.log([1, np.e, np.e**2])) # [0. 1. 2.]

# Aggregate functions
arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))         # 21
print(np.sum(arr, axis=0)) # column sums: [5 7 9]
print(np.sum(arr, axis=1)) # row sums: [6, 15]
print(np.prod(arr))        # 720

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[2.71828183 7.3890561 ]
[2. 3. 4.]
[0. 1. 2.]
21
[5 7 9]
[ 6 15]
720


In [7]:
# Statistical Functions

data = np.random.normal(loc=50, scale=10, size=1000)  # mean=50, std=10

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Std dev:", np.std(data))
print("Variance:", np.var(data))
print("Min:", np.min(data), "Max:", np.max(data))
print("25th percentile:", np.percentile(data, 25))
print("75th percentile:", np.percentile(data, 75))
print("Interquartile range:", np.percentile(data, 75) - np.percentile(data, 25))

Mean: 49.67668092660659
Median: 49.859376280740875
Std dev: 10.030496919151766
Variance: 100.61086844511307
Min: 14.325154746022037 Max: 78.10212179777798
25th percentile: 42.494081168374095
75th percentile: 56.892572419665456
Interquartile range: 14.398491251291361


In [8]:
# Sorting and Searching

arr = np.array([3,1,2,5,4])
sorted_arr = np.sort(arr)          # [1 2 3 4 5]
indices = np.argsort(arr)          # [1 2 0 4 3]  (index of original)

# Searching
print(np.argmax(arr))              # 3 (index of max)
print(np.argmin(arr))              # 1

# Where a condition is True
condition = arr > 2
print(np.where(condition))         # (array([0, 3, 4]),)
print(arr[np.where(condition)])    # [3 5 4]

3
1
(array([0, 3, 4], dtype=int64),)
[3 5 4]


In [9]:
# Unique Values and Counts

vals = np.array([1,2,2,3,3,3,4,4,4,4])
unique, counts = np.unique(vals, return_counts=True)
print("Unique:", unique)           # [1 2 3 4]
print("Counts:", counts)           # [1 2 3 4]

# For 2D
arr2d = np.array([[1,2],[2,3]])
unique_2d, counts_2d = np.unique(arr2d, return_counts=True)
print(unique_2d, counts_2d)

Unique: [1 2 3 4]
Counts: [1 2 3 4]
[1 2 3] [1 2 1]


In [10]:
# Boolean Indexing & Filtering

# Boolean Masks & Conditional Selection
arr = np.arange(1, 11)   # 1 to 10
mask = arr % 2 == 0      # even numbers
print(arr[mask])         # [ 2  4  6  8 10]

# Multiple conditions
mask2 = (arr > 3) & (arr < 8)  # AND: use &, |, ~
print(arr[mask2])              # [4 5 6 7]

# Replace based on condition
arr2 = arr.copy()
arr2[arr2 < 5] = -1
print(arr2)  # [-1 -1 -1 -1  5  6  7  8  9 10]

[ 2  4  6  8 10]
[4 5 6 7]
[-1 -1 -1 -1  5  6  7  8  9 10]


In [11]:
# np.where for Conditional Operations

x = np.array([1,2,3,4,5])
y = np.where(x > 3, 100, 0)   # if x>3 -> 100, else 0
print(y)                       # [  0   0   0 100 100]

# Keep original where False
z = np.where(x % 2 == 0, x, -1)
print(z)                       # [-1  2 -1  4 -1]

# Use where to get indices
indices = np.where(x > 3)
print(indices, x[indices])     # (array([3,4]),) [4 5]

[  0   0   0 100 100]
[-1  2 -1  4 -1]
(array([3, 4], dtype=int64),) [4 5]


In [12]:
# Fancy Indexing

arr = np.array([10,20,30,40,50])
indices = [0, 2, 4]
print(arr[indices])         # [10 30 50]

# Multi-dimensional fancy indexing
arr2d = np.arange(1, 10).reshape(3,3)
rows = [0, 2]
cols = [1, 2]
print(arr2d[rows])           # rows 0 and 2: [[1,2,3],[7,8,9]]
print(arr2d[rows, cols])     # elements at (0,1) and (2,2): [2,9]

# Using boolean arrays as indices
bool_idx = np.array([True, False, True])
print(arr2d[bool_idx])       # selects rows 0 and 2

[10 30 50]
[[1 2 3]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]


In [13]:
# Performance & Vectorization

# Vectorization vs Loops – Performance Benchmarking
size = 1_000_000
a = np.random.rand(size)
b = np.random.rand(size)

# Vectorized dot product
start = time.time()
vec_dot = np.dot(a, b)
vec_time = time.time() - start

# Loop-based dot product
start = time.time()
loop_dot = 0.0
for i in range(size):
    loop_dot += a[i] * b[i]
loop_time = time.time() - start

print(f"Vectorized: {vec_time:.6f} s, result={vec_dot:.4f}")
print(f"Loop:       {loop_time:.6f} s, result={loop_dot:.4f}")
print(f"Speedup: {loop_time/vec_time:.1f}x")

Vectorized: 0.105523 s, result=250198.7804
Loop:       0.475779 s, result=250198.7804
Speedup: 4.5x


In [14]:
# Memory Efficiency – Views vs Copies

# View (no copy of data)
a = np.arange(10)
b = a[2:5]        # view
b[0] = 99
print(a)          # [ 0  1 99  3  4  5  6  7  8  9]  <- original changed

# Copy
c = a[[2,3,4]].copy()  # explicit copy
c[0] = 0
print(a)          # unchanged

[ 0  1 99  3  4  5  6  7  8  9]
[ 0  1 99  3  4  5  6  7  8  9]


In [16]:
# Benchmarking with %timeit (in IPython/Jupyter)

# In a notebook cell:
size = 1_000_000        # you can pick any size
a = np.random.rand(size)
b = np.random.rand(size)
%timeit np.dot(a, b)       # vectorized
%timeit sum(a*b)           # also vectorized but less optimized than np.dot

# Python loop timing
def loop_dot(a, b):
    s = 0.0
    for i in range(len(a)):
        s += a[i]*b[i]
    return s
%timeit loop_dot(a, b)

1.02 ms ± 80.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
91.5 ms ± 15.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
343 ms ± 62 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
# Statistical Analysis on a Dataset

# Simulate dataset: heights (cm) of 10,000 adults, some missing values
np.random.seed(42)
heights = np.random.normal(170, 8, 10000)
heights_with_nan = heights.copy()
heights_with_nan[np.random.choice(10000, 100, replace=False)] = np.nan

# Clean: remove NaN for calculations
clean = heights_with_nan[~np.isnan(heights_with_nan)]

# Analysis
print("=== Height Statistics ===")
print("Count:", len(clean))
print("Mean:", np.mean(clean))
print("Median:", np.median(clean))
print("Std:", np.std(clean))
print("Min:", np.min(clean), "Max:", np.max(clean))
print("1st percentile:", np.percentile(clean, 1))
print("99th percentile:", np.percentile(clean, 99))
print("Skewness:", np.mean(((clean - np.mean(clean))/np.std(clean))**3)) # manual moment

# Binning & histogram (counts per interval)
bins = np.arange(140, 200, 5)
hist, edges = np.histogram(clean, bins=bins)
print("\nHistogram counts per 5cm bin:")
for i in range(len(hist)):
    print(f"{edges[i]:.0f}-{edges[i+1]:.0f} cm: {hist[i]}")

# Filter outliers (beyond 2 std)
lower, upper = np.mean(clean) - 2*np.std(clean), np.mean(clean) + 2*np.std(clean)
outliers = clean[(clean < lower) | (clean > upper)]
print(f"\nOutliers beyond 2σ: {len(outliers)} values")

=== Height Statistics ===
Count: 9900
Mean: 169.97330212103495
Median: 169.97037330895455
Std: 8.021569572131984
Min: 138.62079798705327 Max: 200.82185192523778
1st percentile: 151.47051535742807
99th percentile: 188.59864162107255
Skewness: -0.0012524581466893342

Histogram counts per 5cm bin:
140-145 cm: 7
145-150 cm: 56
150-155 cm: 247
155-160 cm: 747
160-165 cm: 1581
165-170 cm: 2321
170-175 cm: 2320
175-180 cm: 1576
180-185 cm: 740
185-190 cm: 236
190-195 cm: 59

Outliers beyond 2σ: 459 values


In [18]:
#  Data Transformation Pipeline

# Example: normalize, handle missing, one-hot encode small categories
raw = np.array([10, 20, np.nan, 30, 40, 50, 60])

# Replace NaN with median
med = np.nanmedian(raw)
imputed = np.where(np.isnan(raw), med, raw)   # vectorized fill

# Min-max normalization
norm = (imputed - np.min(imputed)) / (np.max(imputed) - np.min(imputed))
print("Normalized:", norm)

# Simulate categorical to one-hot
categories = np.array(['cat', 'dog', 'cat', 'bird', 'dog'])
unique_cats = np.unique(categories)
onehot = np.zeros((len(categories), len(unique_cats)))
for i, cat in enumerate(unique_cats):
    onehot[:, i] = (categories == cat).astype(int)
print("One-hot:\n", onehot)

Normalized: [0.  0.2 0.5 0.4 0.6 0.8 1. ]
One-hot:
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [19]:
# Performance Comparisons

size = 5_000_000
a = np.random.rand(size)
b = np.random.rand(size)

# Compare sum of squares
print("Sum of squares comparison:")
vec_time = %timeit -o -q np.sum(a**2)
loop_time = %timeit -o -q sum(x**2 for x in a)   # using generator
print(f"NumPy vectorized: {vec_time.average:.6f} s")
print(f"Python loop:      {loop_time.average:.6f} s")
print(f"Speedup: {loop_time.average/vec_time.average:.0f}x")

# Element-wise sqrt
print("\nSquare root comparison:")
vec_time2 = %timeit -o -q np.sqrt(a)
loop_time2 = %timeit -o -q [x**0.5 for x in a]   # list comprehension still Python
print(f"NumPy: {vec_time2.average:.6f} s")
print(f"Loop:  {loop_time2.average:.6f} s")
print(f"Speedup: {loop_time2.average/vec_time2.average:.0f}x")

Sum of squares comparison:
NumPy vectorized: 0.028747 s
Python loop:      1.505741 s
Speedup: 52x

Square root comparison:
NumPy: 0.018005 s
Loop:  1.319227 s
Speedup: 73x


In [20]:
# Large Dataset Operations

# Simulate 10 million records with structured dtype (like a pandas alternative)
N = 10_000_000
data = np.zeros(N, dtype=[('id', 'i4'), ('value', 'f4'), ('category', 'U5')])
np.random.seed(123)
data['id'] = np.arange(1, N+1)
data['value'] = np.random.normal(100, 15, N)
cats = ['A','B','C','D','E']
data['category'] = np.random.choice(cats, N)

# Fast filtering & aggregation
print("Sample size:", len(data))
# Filter category 'B'
mask_b = data['category'] == 'B'
filtered = data[mask_b]
print(f"Category B count: {len(filtered)}")
print(f"Mean value (B): {filtered['value'].mean():.2f}")

# Grouped mean without pandas: using numpy tricks
for c in cats:
    mask = data['category'] == c
    mean_val = data['value'][mask].mean()
    print(f"Category {c}: count={mask.sum()}, mean={mean_val:.2f}")

# Time the aggregation (vectorized)
%timeit data['value'][data['category'] == 'B'].mean()
# Compare with loop over all records
%timeit -n1 -r1 [val for (cat, val) in zip(data['category'], data['value']) if cat == 'B']

Sample size: 10000000
Category B count: 2000311
Mean value (B): 100.01
Category A: count=1997311, mean=99.99
Category B: count=2000311, mean=100.01
Category C: count=2000427, mean=100.02
Category D: count=2003455, mean=100.01
Category E: count=1998496, mean=100.00
136 ms ± 13.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
4.42 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
